<?php

/**
 *
 * @file
 * Primary module hooks for migrationwbh module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implement hook_preprocess_page
 */

/**
 * Implements hook_theme().
 */
function migrationwbh_theme($existing, $type, $theme, $path) {
  return [
    'migrationwbh_debug_migrate' => [
      'variables' => [
        'configuration' => null,
        'data' => NULL,
        'raw_data' => NULL,
        'error' => NULL
      ],
      'template' => 'migrationwbh-debug-migrate'
    ]
  ];
}
